[package]
name = "built"
version = "0.6.0"
description = "Provides a crate with information from the time it was built."
repository = "https://github.com/lukaslueg/built"
documentation = "https://docs.rs/built"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["cargo", "build"]
edition = "2021"

[features]
nightly = []
gitoxide = ["gix", "git2"]

[dependencies]
cargo-lock = { version = "8.0", default-features = false }
semver = { version = "1.0", optional = true }
chrono = { version = "0.4", optional = true, default-features = false, features = ["clock"] }
git2 = { version = "0.16", optional = true, default-features = false, features = [] }
gix = { version = "0.43.1", optional = true, default-features = false, features = ["max-performance-safe"] }

[dev-dependencies]
tempfile = "3"

[package.metadata.docs.rs]
features = [ "chrono", "git2", "gitoxide", "semver" ]
